name: Extra-task

on: 
    push:
        branches:
            - main

env:
    DEPLOY_VER: ${{ github.sha }}


jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Print entity of repo
          run: ls -la .
#         - name: Print entity of main.py
#           run: cat main.py
        - name: Print DEPLOY_VER
          run: echo "Hello from $DEPLOY_VER commit"
    
    # second_job:
    #     needs: first_job
    #     runs-on: ubuntu-latest
